// Hand-entered fixture films (TMDB shape), compiled into src/server/db/fixtures/library.json by
// scripts/ingest/build-fixtures.ts. Data is from memory: real TMDB movie ids, approximate
// worldwide grosses (nominal USD), TMDB-style scores. Real ingest replaces this later.
//
// Field key:
//   id   TMDB movie id            t    title                 ot   original title (if different)
//   d    release date             rt   runtime (min)         bo   worldwide gross USD (null = unknown)
//   sc   score (vote avg x10)     st   headline studio       dir  director names (unit if > 1)
//   cast [lead, ...supporting]    g    genres, comma list    tag  tagline
//   kw   keywords, "|" list       c    certs "US|GB|CA|AU|IN|DE" (empty = none for that region)
//   pop  popularity               aw   awards blurb(s), "|" list (written in-house)
//   el   answer eligible (default: true when bo is known)

export interface FixtureFilmSource {
  id: number;
  t: string;
  ot?: string;
  d: string;
  rt: number;
  bo: number | null;
  sc: number;
  st: string;
  dir: string[];
  cast: string[];
  g: string;
  tag: string | null;
  kw: string;
  c: string;
  pop: number;
  aw?: string;
  el?: boolean;
}

export const FIXTURE_FILMS: FixtureFilmSource[] = [
  // Christopher Nolan
  { id: 27205, t: 'Inception', d: '2010-07-15', rt: 148, bo: 839030630, sc: 84, st: 'Warner Bros.', dir: ['Christopher Nolan'], cast: ['Leonardo DiCaprio', 'Joseph Gordon-Levitt', 'Elliot Page', 'Tom Hardy', 'Ken Watanabe'], g: 'Action,Science Fiction,Adventure', tag: 'Your mind is the scene of the crime.', kw: 'dream|heist|subconscious|corporate espionage|limbo', c: 'PG-13|12A|PG|M|UA|12', pop: 92, aw: 'Won 4 Oscars, including Best Cinematography' },
  { id: 155, t: 'The Dark Knight', d: '2008-07-16', rt: 152, bo: 1006234167, sc: 85, st: 'Warner Bros.', dir: ['Christopher Nolan'], cast: ['Christian Bale', 'Heath Ledger', 'Aaron Eckhart', 'Michael Caine', 'Gary Oldman'], g: 'Drama,Action,Crime,Thriller', tag: 'Welcome to a world without rules.', kw: 'joker|vigilante|gotham|chaos|district attorney', c: 'PG-13|12A|PG|M|UA|16', pop: 98, aw: 'Won Best Supporting Actor, awarded posthumously' },
  { id: 49026, t: 'The Dark Knight Rises', d: '2012-07-16', rt: 165, bo: 1081041287, sc: 78, st: 'Warner Bros.', dir: ['Christopher Nolan'], cast: ['Christian Bale', 'Gary Oldman', 'Tom Hardy', 'Joseph Gordon-Levitt', 'Anne Hathaway'], g: 'Action,Crime,Drama,Thriller', tag: 'The Legend Ends', kw: 'terrorist|cat burglar|stock exchange|prison pit', c: 'PG-13|12A|PG|M|UA|12', pop: 70, el: false },
  { id: 272, t: 'Batman Begins', d: '2005-06-10', rt: 140, bo: 373413297, sc: 77, st: 'Warner Bros.', dir: ['Christopher Nolan'], cast: ['Christian Bale', 'Michael Caine', 'Liam Neeson', 'Katie Holmes', 'Gary Oldman'], g: 'Action,Crime,Drama', tag: 'Evil fears the knight.', kw: 'origin story|fear toxin|secret society|billionaire|martial arts', c: 'PG-13|12A|PG|M|UA|12', pop: 65 },
  { id: 157336, t: 'Interstellar', d: '2014-11-05', rt: 169, bo: 701729206, sc: 85, st: 'Paramount', dir: ['Christopher Nolan'], cast: ['Matthew McConaughey', 'Anne Hathaway', 'Michael Caine', 'Jessica Chastain', 'Casey Affleck'], g: 'Adventure,Drama,Science Fiction', tag: 'Mankind was born on Earth. It was never meant to die here.', kw: 'wormhole|black hole|dust storm|time dilation|father daughter relationship', c: 'PG-13|12A|PG|M|UA|12', pop: 120, aw: 'Won Best Visual Effects' },
  { id: 1124, t: 'The Prestige', d: '2006-10-17', rt: 130, bo: 109676311, sc: 82, st: 'Warner Bros.', dir: ['Christopher Nolan'], cast: ['Hugh Jackman', 'Christian Bale', 'Michael Caine', 'Scarlett Johansson', 'Rebecca Hall'], g: 'Drama,Mystery,Science Fiction', tag: 'Are you watching closely?', kw: 'magician|rivalry|victorian london|obsession|teleportation', c: 'PG-13|12A|PG|M||12', pop: 55 },
  { id: 872585, t: 'Oppenheimer', d: '2023-07-19', rt: 181, bo: 975594977, sc: 81, st: 'Universal', dir: ['Christopher Nolan'], cast: ['Cillian Murphy', 'Emily Blunt', 'Matt Damon', 'Robert Downey Jr.', 'Florence Pugh'], g: 'Drama,History', tag: 'The world forever changes.', kw: 'atomic bomb|physicist|manhattan project|security hearing|los alamos', c: 'R|15|14A|M|UA|12', pop: 110, aw: 'Won Best Picture|Won 7 Oscars, including Best Director' },
  { id: 374720, t: 'Dunkirk', d: '2017-07-19', rt: 107, bo: 527016307, sc: 74, st: 'Warner Bros.', dir: ['Christopher Nolan'], cast: ['Fionn Whitehead', 'Tom Glynn-Carney', 'Jack Lowden', 'Harry Styles', 'Aneurin Barnard'], g: 'War,Action,Drama', tag: 'When 400,000 men couldn\'t get home, home came for them.', kw: 'evacuation|beach|world war ii|spitfire|civilian boats', c: 'PG-13|12A|PG|M|UA|12', pop: 50, aw: 'Won 3 Oscars, including Best Film Editing' },
  { id: 77, t: 'Memento', d: '2000-10-11', rt: 113, bo: 39723096, sc: 82, st: 'Newmarket', dir: ['Christopher Nolan'], cast: ['Guy Pearce', 'Carrie-Anne Moss', 'Joe Pantoliano', 'Mark Boone Junior'], g: 'Mystery,Thriller', tag: 'Some memories are best forgotten.', kw: 'amnesia|tattoo|polaroid|revenge|reverse chronology', c: 'R|15|14A|MA15+||16', pop: 40, el: false },

  // The Coens
  { id: 275, t: 'Fargo', d: '1996-03-08', rt: 98, bo: 60611975, sc: 79, st: 'Working Title', dir: ['Joel Coen', 'Ethan Coen'], cast: ['Frances McDormand', 'William H. Macy', 'Steve Buscemi', 'Peter Stormare'], g: 'Crime,Drama,Thriller', tag: 'A lot can happen in the middle of nowhere.', kw: 'kidnapping|minnesota|snow|police chief|wood chipper', c: 'R|18|R|R18+||16', pop: 40, aw: 'Won Best Actress|Won Best Original Screenplay' },
  { id: 6977, t: 'No Country for Old Men', d: '2007-11-08', rt: 122, bo: 171627166, sc: 79, st: 'Miramax', dir: ['Joel Coen', 'Ethan Coen'], cast: ['Tommy Lee Jones', 'Javier Bardem', 'Josh Brolin', 'Woody Harrelson', 'Kelly Macdonald'], g: 'Crime,Drama,Thriller', tag: 'There are no clean getaways.', kw: 'drug money|hitman|texas|coin toss|sheriff', c: 'R|15|14A|MA15+|A|16', pop: 45, aw: 'Won Best Picture|Won 4 Oscars, including Best Adapted Screenplay' },
  { id: 115, t: 'The Big Lebowski', d: '1998-03-06', rt: 117, bo: 46189568, sc: 78, st: 'Working Title', dir: ['Joel Coen', 'Ethan Coen'], cast: ['Jeff Bridges', 'John Goodman', 'Julianne Moore', 'Steve Buscemi', 'Philip Seymour Hoffman'], g: 'Comedy,Crime', tag: 'Times like these call for a Big Lebowski.', kw: 'bowling|mistaken identity|rug|nihilism|ransom', c: 'R|18|14A|MA15+||12', pop: 42 },

  // Quentin Tarantino
  { id: 680, t: 'Pulp Fiction', d: '1994-09-10', rt: 154, bo: 213928762, sc: 85, st: 'Miramax', dir: ['Quentin Tarantino'], cast: ['John Travolta', 'Samuel L. Jackson', 'Uma Thurman', 'Bruce Willis', 'Ving Rhames'], g: 'Thriller,Crime', tag: 'Just because you are a character doesn\'t mean you have character.', kw: 'hitman|briefcase|boxer|nonlinear timeline|dance contest', c: 'R|18|R|R18+|A|16', pop: 85, aw: 'Won Best Original Screenplay' },
  { id: 24, t: 'Kill Bill: Vol. 1', d: '2003-10-10', rt: 111, bo: 180906076, sc: 80, st: 'Miramax', dir: ['Quentin Tarantino'], cast: ['Uma Thurman', 'Lucy Liu', 'Vivica A. Fox', 'Daryl Hannah', 'David Carradine'], g: 'Action,Crime', tag: 'Go for the kill.', kw: 'revenge|katana|assassin|coma|tokyo', c: 'R|18|R|R18+|A|18', pop: 60 },
  { id: 16869, t: 'Inglourious Basterds', d: '2009-08-02', rt: 153, bo: 321457747, sc: 82, st: 'Universal', dir: ['Quentin Tarantino'], cast: ['Brad Pitt', 'Mélanie Laurent', 'Christoph Waltz', 'Eli Roth', 'Michael Fassbender'], g: 'Drama,Thriller,War', tag: 'Once upon a time in Nazi occupied France...', kw: 'world war ii|cinema|alternate history|scalping|film premiere', c: 'R|18|14A|MA15+|A|16', pop: 66, aw: 'Won Best Supporting Actor' },
  { id: 68718, t: 'Django Unchained', d: '2012-12-25', rt: 165, bo: 425368238, sc: 82, st: 'Sony', dir: ['Quentin Tarantino'], cast: ['Jamie Foxx', 'Christoph Waltz', 'Leonardo DiCaprio', 'Kerry Washington', 'Samuel L. Jackson'], g: 'Drama,Western', tag: 'Life, liberty and the pursuit of vengeance.', kw: 'bounty hunter|slavery|plantation|rescue|dentist', c: 'R|18|18A|R18+|A|16', pop: 72, aw: 'Won Best Original Screenplay|Won Best Supporting Actor' },
  { id: 466272, t: 'Once Upon a Time... in Hollywood', d: '2019-07-24', rt: 162, bo: 374343626, sc: 74, st: 'Sony', dir: ['Quentin Tarantino'], cast: ['Leonardo DiCaprio', 'Brad Pitt', 'Margot Robbie', 'Emile Hirsch', 'Margaret Qualley'], g: 'Comedy,Drama,Thriller', tag: 'In this town, it can all change. Like that.', kw: 'stuntman|fading actor|1960s|los angeles|cult', c: 'R|18|14A|MA15+|A|16', pop: 58, aw: 'Won Best Supporting Actor|Won Best Production Design' },
  { id: 500, t: 'Reservoir Dogs', d: '1992-09-02', rt: 99, bo: 2832029, sc: 81, st: 'Miramax', dir: ['Quentin Tarantino'], cast: ['Harvey Keitel', 'Tim Roth', 'Michael Madsen', 'Chris Penn', 'Steve Buscemi'], g: 'Crime,Thriller', tag: 'Every dog has his day.', kw: 'heist gone wrong|warehouse|undercover cop|code names', c: 'R|18|R|R18+||18', pop: 38, el: false },

  // Steven Spielberg
  { id: 578, t: 'Jaws', d: '1975-06-20', rt: 124, bo: 476512065, sc: 77, st: 'Universal', dir: ['Steven Spielberg'], cast: ['Roy Scheider', 'Robert Shaw', 'Richard Dreyfuss', 'Lorraine Gary', 'Murray Hamilton'], g: 'Horror,Thriller,Adventure', tag: 'You\'ll never go in the water again.', kw: 'shark|beach town|police chief|fishing boat|summer', c: 'PG|12A|PG|M||12', pop: 50, aw: 'Won 3 Oscars, including Best Original Score' },
  { id: 601, t: 'E.T. the Extra-Terrestrial', d: '1982-06-11', rt: 115, bo: 792910554, sc: 75, st: 'Universal', dir: ['Steven Spielberg'], cast: ['Henry Thomas', 'Drew Barrymore', 'Robert MacNaughton', 'Dee Wallace', 'Peter Coyote'], g: 'Science Fiction,Adventure,Family,Fantasy', tag: 'He is afraid. He is totally alone. He is 3 million light years from home.', kw: 'alien|bicycle|friendship|suburb|phone home', c: 'PG|U|G|PG||6', pop: 45, aw: 'Won 4 Oscars, including Best Original Score' },
  { id: 329, t: 'Jurassic Park', d: '1993-06-11', rt: 127, bo: 1058682142, sc: 79, st: 'Universal', dir: ['Steven Spielberg'], cast: ['Sam Neill', 'Laura Dern', 'Jeff Goldblum', 'Richard Attenborough', 'Bob Peck'], g: 'Adventure,Science Fiction', tag: 'An adventure 65 million years in the making.', kw: 'dinosaur|theme park|island|cloning|paleontologist', c: 'PG-13|PG|PG|M|U|12', pop: 80, aw: 'Won 3 Oscars, including Best Visual Effects' },
  { id: 424, t: 'Schindler\'s List', d: '1993-12-15', rt: 195, bo: 322161245, sc: 86, st: 'Universal', dir: ['Steven Spielberg'], cast: ['Liam Neeson', 'Ben Kingsley', 'Ralph Fiennes', 'Caroline Goodall', 'Jonathan Sagall'], g: 'Drama,History,War', tag: 'Whoever saves one life, saves the world entire.', kw: 'holocaust|factory|list|krakow|black and white', c: 'R|15|14A|M||12', pop: 60, aw: 'Won Best Picture|Won 7 Oscars, including Best Director' },
  { id: 857, t: 'Saving Private Ryan', d: '1998-07-24', rt: 169, bo: 482349603, sc: 82, st: 'DreamWorks', dir: ['Steven Spielberg'], cast: ['Tom Hanks', 'Edward Burns', 'Matt Damon', 'Tom Sizemore', 'Barry Pepper'], g: 'Drama,History,War', tag: 'The mission is a man.', kw: 'd-day|normandy|rescue mission|sniper|world war ii', c: 'R|15|14A|MA15+|A|16', pop: 62, aw: 'Won Best Director|Won 5 Oscars, including Best Cinematography' },
  { id: 85, t: 'Raiders of the Lost Ark', d: '1981-06-12', rt: 115, bo: 389925971, sc: 79, st: 'Lucasfilm', dir: ['Steven Spielberg'], cast: ['Harrison Ford', 'Karen Allen', 'Paul Freeman', 'John Rhys-Davies', 'Ronald Lacey'], g: 'Adventure,Action', tag: 'The return of the great adventure.', kw: 'archaeologist|ark of the covenant|nazis|whip|snakes', c: 'PG|PG|PG|M||12', pop: 55, aw: 'Won 4 Oscars, including Best Film Editing' },
  { id: 640, t: 'Catch Me If You Can', d: '2002-12-25', rt: 141, bo: 352114312, sc: 80, st: 'DreamWorks', dir: ['Steven Spielberg'], cast: ['Leonardo DiCaprio', 'Tom Hanks', 'Christopher Walken', 'Martin Sheen', 'Amy Adams'], g: 'Drama,Crime', tag: 'The true story of a real fake.', kw: 'con artist|forgery|fbi agent|pilot|cat and mouse', c: 'PG-13|12A|PG|M||6', pop: 58 },

  // Martin Scorsese
  { id: 103, t: 'Taxi Driver', d: '1976-02-09', rt: 114, bo: 28262574, sc: 81, st: 'Sony', dir: ['Martin Scorsese'], cast: ['Robert De Niro', 'Jodie Foster', 'Cybill Shepherd', 'Albert Brooks', 'Harvey Keitel'], g: 'Crime,Drama', tag: 'On every street in every city, there\'s a nobody who dreams of being a somebody.', kw: 'insomnia|vigilante|new york city|loneliness|mohawk', c: 'R|18|R|R18+||16', pop: 45 },
  { id: 769, t: 'GoodFellas', d: '1990-09-12', rt: 145, bo: 46836214, sc: 85, st: 'Warner Bros.', dir: ['Martin Scorsese'], cast: ['Robert De Niro', 'Ray Liotta', 'Joe Pesci', 'Lorraine Bracco', 'Paul Sorvino'], g: 'Drama,Crime', tag: 'Three decades of life in the Mafia.', kw: 'mafia|gangster|witness protection|airport heist|cocaine', c: 'R|18|R|R18+||16', pop: 52, aw: 'Won Best Supporting Actor' },
  { id: 1422, t: 'The Departed', d: '2006-10-05', rt: 151, bo: 291465034, sc: 82, st: 'Warner Bros.', dir: ['Martin Scorsese'], cast: ['Leonardo DiCaprio', 'Matt Damon', 'Jack Nicholson', 'Mark Wahlberg', 'Martin Sheen'], g: 'Drama,Thriller,Crime', tag: 'Cops or criminals. When you\'re facing a loaded gun, what\'s the difference?', kw: 'undercover cop|mole|boston|irish mob|state police', c: 'R|18|18A|MA15+|A|16', pop: 60, aw: 'Won Best Picture|Won 4 Oscars, including Best Director' },
  { id: 106646, t: 'The Wolf of Wall Street', d: '2013-12-25', rt: 180, bo: 392000694, sc: 80, st: 'Paramount', dir: ['Martin Scorsese'], cast: ['Leonardo DiCaprio', 'Jonah Hill', 'Margot Robbie', 'Matthew McConaughey', 'Kyle Chandler'], g: 'Crime,Drama,Comedy', tag: 'Earn. Spend. Party.', kw: 'stockbroker|securities fraud|excess|quaaludes|yacht', c: 'R|18|18A|R18+|A|16', pop: 75 },
  { id: 11324, t: 'Shutter Island', d: '2010-02-14', rt: 138, bo: 294804195, sc: 82, st: 'Paramount', dir: ['Martin Scorsese'], cast: ['Leonardo DiCaprio', 'Mark Ruffalo', 'Ben Kingsley', 'Emily Mortimer', 'Michelle Williams'], g: 'Drama,Thriller,Mystery', tag: 'Someone is missing.', kw: 'psychiatric hospital|island|us marshal|hurricane|1950s', c: 'R|15|14A|MA15+|A|16', pop: 70 },
  { id: 398978, t: 'The Irishman', d: '2019-11-01', rt: 209, bo: null, sc: 76, st: 'Netflix', dir: ['Martin Scorsese'], cast: ['Robert De Niro', 'Al Pacino', 'Joe Pesci', 'Harvey Keitel', 'Ray Romano'], g: 'Crime,Drama,History', tag: 'His story changed history.', kw: 'hitman|labor union|de-aging|truck driver|mafia', c: 'R|15|14A|MA15+||16', pop: 35 },

  // David Fincher
  { id: 550, t: 'Fight Club', d: '1999-10-15', rt: 139, bo: 100853753, sc: 84, st: '20th Century', dir: ['David Fincher'], cast: ['Edward Norton', 'Brad Pitt', 'Helena Bonham Carter', 'Meat Loaf', 'Jared Leto'], g: 'Drama', tag: 'Mischief. Mayhem. Soap.', kw: 'insomnia|split personality|underground fighting|soap|anti-consumerism', c: 'R|18|R|R18+|A|18', pop: 88 },
  { id: 807, t: 'Se7en', d: '1995-09-22', rt: 127, bo: 327311859, sc: 84, st: 'New Line', dir: ['David Fincher'], cast: ['Brad Pitt', 'Morgan Freeman', 'Gwyneth Paltrow', 'Kevin Spacey', 'R. Lee Ermey'], g: 'Crime,Mystery,Thriller', tag: 'Seven deadly sins. Seven ways to die.', kw: 'serial killer|detective|seven deadly sins|rain|box', c: 'R|18|R|R18+|A|16', pop: 70 },
  { id: 37799, t: 'The Social Network', d: '2010-10-01', rt: 121, bo: 224920315, sc: 74, st: 'Sony', dir: ['David Fincher'], cast: ['Jesse Eisenberg', 'Andrew Garfield', 'Justin Timberlake', 'Armie Hammer', 'Max Minghella'], g: 'Drama', tag: 'You don\'t get to 500 million friends without making a few enemies.', kw: 'harvard|lawsuit|startup|social media|deposition', c: 'PG-13|12A|PG|M|UA|12', pop: 45, aw: 'Won Best Adapted Screenplay' },
  { id: 210577, t: 'Gone Girl', d: '2014-10-01', rt: 149, bo: 369330363, sc: 79, st: '20th Century', dir: ['David Fincher'], cast: ['Ben Affleck', 'Rosamund Pike', 'Neil Patrick Harris', 'Tyler Perry', 'Carrie Coon'], g: 'Mystery,Thriller,Drama', tag: 'You don\'t know what you\'ve got \'til it\'s gone.', kw: 'missing wife|media circus|marriage|missouri|diary', c: 'R|18|14A|MA15+|A|16', pop: 60 },
  { id: 1949, t: 'Zodiac', d: '2007-03-02', rt: 157, bo: 84785914, sc: 75, st: 'Paramount', dir: ['David Fincher'], cast: ['Jake Gyllenhaal', 'Mark Ruffalo', 'Robert Downey Jr.', 'Anthony Edwards', 'Brian Cox'], g: 'Crime,Drama,Mystery,Thriller', tag: 'There\'s more than one way to lose your life to a killer.', kw: 'serial killer|cipher|cartoonist|san francisco|obsession', c: 'R|15|14A|MA15+||16', pop: 38, el: false },

  // Denis Villeneuve
  { id: 438631, t: 'Dune', d: '2021-09-15', rt: 155, bo: 402027830, sc: 78, st: 'Warner Bros.', dir: ['Denis Villeneuve'], cast: ['Timothée Chalamet', 'Rebecca Ferguson', 'Oscar Isaac', 'Josh Brolin', 'Stellan Skarsgård'], g: 'Science Fiction,Adventure', tag: 'Beyond fear, destiny awaits.', kw: 'desert planet|spice|chosen one|sandworm|noble house', c: 'PG-13|12A|PG|M|UA|12', pop: 95, aw: 'Won 6 Oscars, including Best Cinematography' },
  { id: 693134, t: 'Dune: Part Two', d: '2024-02-27', rt: 167, bo: 714444358, sc: 82, st: 'Warner Bros.', dir: ['Denis Villeneuve'], cast: ['Timothée Chalamet', 'Zendaya', 'Rebecca Ferguson', 'Javier Bardem', 'Josh Brolin'], g: 'Science Fiction,Adventure', tag: 'Long live the fighters.', kw: 'desert planet|prophecy|revenge|holy war|sandworm', c: 'PG-13|12A|PG|M|UA|12', pop: 105, aw: 'Won Best Sound|Won Best Visual Effects' },
  { id: 329865, t: 'Arrival', d: '2016-11-10', rt: 116, bo: 203388186, sc: 76, st: 'Paramount', dir: ['Denis Villeneuve'], cast: ['Amy Adams', 'Jeremy Renner', 'Forest Whitaker', 'Michael Stuhlbarg', 'Tzi Ma'], g: 'Drama,Science Fiction,Mystery', tag: 'Why are they here?', kw: 'linguist|first contact|language|time|alien spacecraft', c: 'PG-13|12A|PG|M|UA|12', pop: 48, aw: 'Won Best Sound Editing' },
  { id: 335984, t: 'Blade Runner 2049', d: '2017-10-04', rt: 164, bo: 259239658, sc: 76, st: 'Warner Bros.', dir: ['Denis Villeneuve'], cast: ['Ryan Gosling', 'Harrison Ford', 'Ana de Armas', 'Sylvia Hoeks', 'Robin Wright'], g: 'Science Fiction,Drama', tag: 'The key to the future is finally unearthed.', kw: 'replicant|dystopia|hologram|memory|los angeles', c: 'R|15|14A|M|UA|12', pop: 55, aw: 'Won Best Cinematography|Won Best Visual Effects' },

  // James Cameron
  { id: 280, t: 'Terminator 2: Judgment Day', d: '1991-07-03', rt: 137, bo: 520881154, sc: 81, st: 'Sony', dir: ['James Cameron'], cast: ['Arnold Schwarzenegger', 'Linda Hamilton', 'Edward Furlong', 'Robert Patrick', 'Earl Boen'], g: 'Action,Thriller,Science Fiction', tag: 'It\'s nothing personal.', kw: 'cyborg|time travel|liquid metal|judgment day|protector', c: 'R|15|14A|M||16', pop: 60, aw: 'Won 4 Oscars, including Best Visual Effects' },
  { id: 597, t: 'Titanic', d: '1997-11-18', rt: 194, bo: 2264743305, sc: 79, st: 'Paramount', dir: ['James Cameron'], cast: ['Leonardo DiCaprio', 'Kate Winslet', 'Billy Zane', 'Kathy Bates', 'Frances Fisher'], g: 'Drama,Romance', tag: 'Nothing on Earth could come between them.', kw: 'shipwreck|iceberg|forbidden love|ocean liner|1910s', c: 'PG-13|12A|PG|M|UA|12', pop: 100, aw: 'Won Best Picture|Won 11 Oscars, including Best Director' },
  { id: 19995, t: 'Avatar', d: '2009-12-15', rt: 162, bo: 2923706026, sc: 76, st: '20th Century', dir: ['James Cameron'], cast: ['Sam Worthington', 'Zoe Saldaña', 'Sigourney Weaver', 'Stephen Lang', 'Michelle Rodriguez'], g: 'Action,Adventure,Fantasy,Science Fiction', tag: 'Enter the world of Pandora.', kw: 'alien planet|paraplegic|mining colony|avatar|clash of cultures', c: 'PG-13|12A|PG|M|UA|12', pop: 115, aw: 'Won 3 Oscars, including Best Cinematography' },
  { id: 679, t: 'Aliens', d: '1986-07-18', rt: 137, bo: 131060248, sc: 79, st: '20th Century', dir: ['James Cameron'], cast: ['Sigourney Weaver', 'Michael Biehn', 'Carrie Henn', 'Paul Reiser', 'Lance Henriksen'], g: 'Action,Thriller,Science Fiction', tag: 'This time it\'s war.', kw: 'space marine|xenomorph|colony|android|queen alien', c: 'R|15|14A|M||16', pop: 48, aw: 'Won Best Visual Effects|Won Best Sound Effects Editing' },

  // Peter Jackson
  { id: 120, t: 'The Lord of the Rings: The Fellowship of the Ring', d: '2001-12-18', rt: 179, bo: 887934303, sc: 84, st: 'New Line', dir: ['Peter Jackson'], cast: ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen', 'Sean Astin', 'Cate Blanchett'], g: 'Adventure,Fantasy,Action', tag: 'One ring to rule them all.', kw: 'hobbit|wizard|quest|magic ring|elves', c: 'PG-13|PG|PG|M|U|12', pop: 95, aw: 'Won 4 Oscars, including Best Cinematography' },
  { id: 121, t: 'The Lord of the Rings: The Two Towers', d: '2002-12-18', rt: 179, bo: 926287400, sc: 84, st: 'New Line', dir: ['Peter Jackson'], cast: ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen', 'Sean Astin', 'Orlando Bloom'], g: 'Adventure,Fantasy,Action', tag: 'A New Power Is Rising.', kw: 'siege|ents|wizard|hobbit|fortress', c: 'PG-13|12A|PG|M|U|12', pop: 80, aw: 'Won Best Visual Effects|Won Best Sound Editing', el: false },
  { id: 122, t: 'The Lord of the Rings: The Return of the King', d: '2003-12-01', rt: 201, bo: 1118888979, sc: 85, st: 'New Line', dir: ['Peter Jackson'], cast: ['Elijah Wood', 'Ian McKellen', 'Viggo Mortensen', 'Sean Astin', 'Cate Blanchett'], g: 'Adventure,Fantasy,Action', tag: 'The eye of the enemy is moving.', kw: 'final battle|volcano|king|hobbit|siege', c: 'PG-13|12A|PG|M|U|12', pop: 90, aw: 'Won Best Picture|Won all 11 Oscars it was nominated for' },

  // Greta Gerwig
  { id: 391713, t: 'Lady Bird', d: '2017-11-03', rt: 94, bo: 78964474, sc: 73, st: 'A24', dir: ['Greta Gerwig'], cast: ['Saoirse Ronan', 'Laurie Metcalf', 'Tracy Letts', 'Lucas Hedges', 'Timothée Chalamet'], g: 'Drama,Comedy', tag: 'Fly away home.', kw: 'coming of age|mother daughter relationship|sacramento|catholic school|college applications', c: 'R|15|14A|M||0', pop: 30 },
  { id: 331482, t: 'Little Women', d: '2019-12-25', rt: 135, bo: 218866360, sc: 79, st: 'Sony', dir: ['Greta Gerwig'], cast: ['Saoirse Ronan', 'Emma Watson', 'Florence Pugh', 'Eliza Scanlen', 'Laura Dern'], g: 'Drama,Romance,History', tag: 'Own your story.', kw: 'sisters|writer|civil war|massachusetts|literary adaptation', c: 'PG|U|PG|PG|U|0', pop: 35, aw: 'Won Best Costume Design' },
  { id: 346698, t: 'Barbie', d: '2023-07-19', rt: 114, bo: 1445638421, sc: 70, st: 'Warner Bros.', dir: ['Greta Gerwig'], cast: ['Margot Robbie', 'Ryan Gosling', 'America Ferrera', 'Ariana Greenblatt', 'Kate McKinnon'], g: 'Comedy,Adventure,Fantasy', tag: 'She\'s everything. He\'s just Ken.', kw: 'doll|patriarchy|real world|existential crisis|pink', c: 'PG-13|12A|PG|PG|UA|6', pop: 100, aw: 'Won Best Original Song' },

  // The Russo Brothers and Marvel Studios
  { id: 299536, t: 'Avengers: Infinity War', d: '2018-04-25', rt: 149, bo: 2052415039, sc: 82, st: 'Marvel Studios', dir: ['Anthony Russo', 'Joe Russo'], cast: ['Robert Downey Jr.', 'Chris Hemsworth', 'Mark Ruffalo', 'Chris Evans', 'Scarlett Johansson'], g: 'Adventure,Action,Science Fiction', tag: 'An entire universe. Once and for all.', kw: 'superhero|infinity stones|team up|snap|cliffhanger', c: 'PG-13|12A|PG|M|UA|12', pop: 110 },
  { id: 299534, t: 'Avengers: Endgame', d: '2019-04-24', rt: 181, bo: 2799439100, sc: 82, st: 'Marvel Studios', dir: ['Anthony Russo', 'Joe Russo'], cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson'], g: 'Adventure,Science Fiction,Action', tag: 'Avenge the fallen.', kw: 'superhero|time heist|sacrifice|quantum realm|final battle', c: 'PG-13|12A|PG|M|UA|12', pop: 112 },
  { id: 100402, t: 'Captain America: The Winter Soldier', d: '2014-03-20', rt: 136, bo: 714401889, sc: 77, st: 'Marvel Studios', dir: ['Anthony Russo', 'Joe Russo'], cast: ['Chris Evans', 'Scarlett Johansson', 'Sebastian Stan', 'Anthony Mackie', 'Cobie Smulders'], g: 'Action,Adventure,Science Fiction', tag: 'In heroes we trust.', kw: 'superhero|conspiracy|brainwashing|helicarrier|spy', c: 'PG-13|12A|PG|M|UA|12', pop: 60, el: false },
  { id: 1726, t: 'Iron Man', d: '2008-04-30', rt: 126, bo: 585174222, sc: 76, st: 'Marvel Studios', dir: ['Jon Favreau'], cast: ['Robert Downey Jr.', 'Terrence Howard', 'Jeff Bridges', 'Gwyneth Paltrow', 'Leslie Bibb'], g: 'Action,Science Fiction,Adventure', tag: 'Heroes aren\'t born. They\'re built.', kw: 'superhero|armor|weapons manufacturer|cave|billionaire', c: 'PG-13|12A|PG|M|UA|12', pop: 75 },
  { id: 24428, t: 'The Avengers', d: '2012-04-25', rt: 143, bo: 1518815515, sc: 77, st: 'Marvel Studios', dir: ['Joss Whedon'], cast: ['Robert Downey Jr.', 'Chris Evans', 'Mark Ruffalo', 'Chris Hemsworth', 'Scarlett Johansson'], g: 'Science Fiction,Action,Adventure', tag: 'Some assembly required.', kw: 'superhero|alien invasion|new york city|team up|tesseract', c: 'PG-13|12A|PG|M|UA|12', pop: 90 },
  { id: 284054, t: 'Black Panther', d: '2018-02-13', rt: 135, bo: 1349926083, sc: 74, st: 'Marvel Studios', dir: ['Ryan Coogler'], cast: ['Chadwick Boseman', 'Michael B. Jordan', 'Lupita Nyong\'o', 'Danai Gurira', 'Martin Freeman'], g: 'Action,Adventure,Science Fiction', tag: 'Long live the king.', kw: 'superhero|hidden kingdom|vibranium|succession|africa', c: 'PG-13|12A|PG|M|UA|12', pop: 70, aw: 'Won 3 Oscars, including Best Costume Design' },

  // Daniels, Lord and Miller, The Wachowskis
  { id: 545611, t: 'Everything Everywhere All at Once', d: '2022-03-24', rt: 140, bo: 141295742, sc: 78, st: 'A24', dir: ['Daniel Kwan', 'Daniel Scheinert'], cast: ['Michelle Yeoh', 'Stephanie Hsu', 'Ke Huy Quan', 'James Hong', 'Jamie Lee Curtis'], g: 'Action,Adventure,Science Fiction', tag: 'The universe is so much bigger than you realize.', kw: 'multiverse|laundromat|tax audit|mother daughter relationship|everything bagel', c: 'R|15|14A|MA15+|A|12', pop: 60, aw: 'Won Best Picture|Won 7 Oscars, including Best Director' },
  { id: 137106, t: 'The Lego Movie', d: '2014-02-06', rt: 100, bo: 468060692, sc: 74, st: 'Warner Bros.', dir: ['Phil Lord', 'Christopher Miller'], cast: ['Chris Pratt', 'Will Ferrell', 'Elizabeth Banks', 'Will Arnett', 'Morgan Freeman'], g: 'Animation,Family,Adventure,Comedy,Fantasy', tag: 'The story of a nobody who saved everybody.', kw: 'toy|chosen one|construction worker|prophecy|glue', c: 'PG|U|G|PG|U|0', pop: 45 },
  { id: 64688, t: '21 Jump Street', d: '2012-03-12', rt: 109, bo: 201585328, sc: 69, st: 'Sony', dir: ['Phil Lord', 'Christopher Miller'], cast: ['Jonah Hill', 'Channing Tatum', 'Brie Larson', 'Dave Franco', 'Rob Riggle'], g: 'Action,Comedy,Crime', tag: 'They\'re not who they used to be.', kw: 'undercover cop|high school|buddy cop|synthetic drug|prom', c: 'R|15|14A|MA15+|A|12', pop: 40 },
  { id: 603, t: 'The Matrix', d: '1999-03-31', rt: 136, bo: 463517383, sc: 82, st: 'Warner Bros.', dir: ['Lana Wachowski', 'Lilly Wachowski'], cast: ['Keanu Reeves', 'Laurence Fishburne', 'Carrie-Anne Moss', 'Hugo Weaving', 'Joe Pantoliano'], g: 'Action,Science Fiction', tag: 'Welcome to the Real World.', kw: 'simulated reality|hacker|red pill|bullet time|artificial intelligence', c: 'R|15|R|M|A|16', pop: 90, aw: 'Won 4 Oscars, including Best Visual Effects' },

  // Classics
  { id: 238, t: 'The Godfather', d: '1972-03-14', rt: 175, bo: 250341816, sc: 87, st: 'Paramount', dir: ['Francis Ford Coppola'], cast: ['Marlon Brando', 'Al Pacino', 'James Caan', 'Richard S. Castellano', 'Robert Duvall'], g: 'Drama,Crime', tag: 'An offer you can\'t refuse.', kw: 'mafia|crime family|succession|new york city|horse head', c: 'R|15|14A|MA15+|A|16', pop: 95, aw: 'Won Best Picture|Won Best Actor' },
  { id: 240, t: 'The Godfather Part II', d: '1974-12-20', rt: 202, bo: 102600000, sc: 86, st: 'Paramount', dir: ['Francis Ford Coppola'], cast: ['Al Pacino', 'Robert Duvall', 'Diane Keaton', 'Robert De Niro', 'John Cazale'], g: 'Drama,Crime', tag: 'The rise and fall of the Corleone empire.', kw: 'mafia|sequel|cuba|immigrant|betrayal', c: 'R|15|14A|MA15+||16', pop: 60, aw: 'Won Best Picture|Won 6 Oscars, including Best Supporting Actor', el: false },
  { id: 11, t: 'Star Wars', d: '1977-05-25', rt: 121, bo: 775398007, sc: 82, st: 'Lucasfilm', dir: ['George Lucas'], cast: ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher', 'Peter Cushing', 'Alec Guinness'], g: 'Adventure,Action,Science Fiction', tag: 'A long time ago in a galaxy far, far away...', kw: 'space opera|rebellion|princess|death star|farm boy', c: 'PG|U|PG|PG|U|12', pop: 85, aw: 'Won 6 Oscars, including Best Original Score' },
  { id: 1891, t: 'The Empire Strikes Back', d: '1980-05-20', rt: 124, bo: 538375067, sc: 84, st: 'Lucasfilm', dir: ['Irvin Kershner'], cast: ['Mark Hamill', 'Harrison Ford', 'Carrie Fisher', 'Billy Dee Williams', 'Anthony Daniels'], g: 'Adventure,Action,Science Fiction', tag: 'The Adventure Continues...', kw: 'space opera|ice planet|jedi training|cloud city|father', c: 'PG|U|PG|PG||12', pop: 70, aw: 'Won Best Sound', el: false },
  { id: 278, t: 'The Shawshank Redemption', d: '1994-09-23', rt: 142, bo: 28341469, sc: 87, st: 'Castle Rock', dir: ['Frank Darabont'], cast: ['Tim Robbins', 'Morgan Freeman', 'Bob Gunton', 'William Sadler', 'Clancy Brown'], g: 'Drama,Crime', tag: 'Fear can hold you prisoner. Hope can set you free.', kw: 'prison|friendship|wrongful conviction|escape|hope', c: 'R|15|14A|MA15+||12', pop: 100 },
  { id: 13, t: 'Forrest Gump', d: '1994-06-23', rt: 142, bo: 678226465, sc: 85, st: 'Paramount', dir: ['Robert Zemeckis'], cast: ['Tom Hanks', 'Robin Wright', 'Gary Sinise', 'Sally Field', 'Mykelti Williamson'], g: 'Comedy,Drama,Romance', tag: 'The world will never be the same once you\'ve seen it through the eyes of Forrest Gump.', kw: 'vietnam war|running|shrimp boat|historical events|box of chocolates', c: 'PG-13|12|PG|M||12', pop: 90, aw: 'Won Best Picture|Won 6 Oscars, including Best Actor' },
  { id: 105, t: 'Back to the Future', d: '1985-07-03', rt: 116, bo: 381109762, sc: 83, st: 'Universal', dir: ['Robert Zemeckis'], cast: ['Michael J. Fox', 'Christopher Lloyd', 'Lea Thompson', 'Crispin Glover', 'Thomas F. Wilson'], g: 'Adventure,Comedy,Science Fiction', tag: 'He\'s the only kid ever to get into trouble before he was born.', kw: 'time travel|delorean|1950s|skateboarding|high school dance', c: 'PG|PG|PG|PG|U|6', pop: 70, aw: 'Won Best Sound Effects Editing' },
  { id: 8358, t: 'Cast Away', d: '2000-12-22', rt: 143, bo: 429632142, sc: 77, st: '20th Century', dir: ['Robert Zemeckis'], cast: ['Tom Hanks', 'Helen Hunt', 'Nick Searcy', 'Chris Noth'], g: 'Adventure,Drama', tag: 'At the edge of the world, his journey begins.', kw: 'deserted island|plane crash|volleyball|survival|courier', c: 'PG-13|12|PG|M||12', pop: 45, el: false },
  { id: 274, t: 'The Silence of the Lambs', d: '1991-02-14', rt: 119, bo: 272742922, sc: 83, st: 'Orion', dir: ['Jonathan Demme'], cast: ['Jodie Foster', 'Anthony Hopkins', 'Scott Glenn', 'Ted Levine', 'Anthony Heald'], g: 'Crime,Drama,Thriller', tag: 'To enter the mind of a killer, she must challenge the mind of a madman.', kw: 'fbi trainee|serial killer|cannibal|psychiatrist|moth', c: 'R|18|R|R18+||16', pop: 60, aw: 'Won Best Picture|Won all five major Oscars' },
  { id: 348, t: 'Alien', d: '1979-05-25', rt: 117, bo: 104931801, sc: 81, st: '20th Century', dir: ['Ridley Scott'], cast: ['Tom Skerritt', 'Sigourney Weaver', 'Veronica Cartwright', 'Harry Dean Stanton', 'John Hurt'], g: 'Horror,Science Fiction', tag: 'In space no one can hear you scream.', kw: 'spaceship|xenomorph|android|distress signal|chestburster', c: 'R|15|R|M||16', pop: 50, aw: 'Won Best Visual Effects', el: false },
  { id: 98, t: 'Gladiator', d: '2000-05-04', rt: 155, bo: 465516248, sc: 82, st: 'DreamWorks', dir: ['Ridley Scott'], cast: ['Russell Crowe', 'Joaquin Phoenix', 'Connie Nielsen', 'Oliver Reed', 'Richard Harris'], g: 'Action,Drama,Adventure', tag: 'What we do in life echoes in eternity.', kw: 'ancient rome|general|arena|revenge|emperor', c: 'R|15|14A|MA15+|A|16', pop: 85, aw: 'Won Best Picture|Won Best Actor' },
  { id: 694, t: 'The Shining', d: '1980-05-23', rt: 144, bo: 46998772, sc: 82, st: 'Warner Bros.', dir: ['Stanley Kubrick'], cast: ['Jack Nicholson', 'Shelley Duvall', 'Danny Lloyd', 'Scatman Crothers', 'Barry Nelson'], g: 'Horror,Thriller', tag: 'A masterpiece of modern horror.', kw: 'hotel|writer|winter|psychic|isolation', c: 'R|18|R|MA15+||16', pop: 55 },
  { id: 1366, t: 'Rocky', d: '1976-11-21', rt: 120, bo: 225000000, sc: 78, st: 'United Artists', dir: ['John G. Avildsen'], cast: ['Sylvester Stallone', 'Talia Shire', 'Burt Young', 'Carl Weathers', 'Burgess Meredith'], g: 'Drama', tag: 'His whole life was a million-to-one shot.', kw: 'boxing|underdog|philadelphia|training montage|heavyweight', c: 'PG|PG|PG|PG||12', pop: 45, aw: 'Won Best Picture|Won Best Director' },
  { id: 949, t: 'Heat', d: '1995-12-15', rt: 170, bo: 187436818, sc: 79, st: 'Warner Bros.', dir: ['Michael Mann'], cast: ['Al Pacino', 'Robert De Niro', 'Val Kilmer', 'Jon Voight', 'Tom Sizemore'], g: 'Action,Crime,Drama', tag: 'A Los Angeles crime saga.', kw: 'bank robbery|detective|los angeles|shootout|professional thief', c: 'R|15|14A|MA15+||16', pop: 45, el: false },

  // Animation
  { id: 862, t: 'Toy Story', d: '1995-11-22', rt: 81, bo: 373554033, sc: 80, st: 'Pixar', dir: ['John Lasseter'], cast: ['Tom Hanks', 'Tim Allen', 'Don Rickles', 'Jim Varney', 'Wallace Shawn'], g: 'Animation,Adventure,Family,Comedy', tag: 'Hang on for the comedy that goes to infinity and beyond!', kw: 'toy|rivalry|space ranger|cowboy|neighbor', c: 'G|U|G|G|U|0', pop: 80 },
  { id: 12, t: 'Finding Nemo', d: '2003-05-30', rt: 100, bo: 940335536, sc: 78, st: 'Pixar', dir: ['Andrew Stanton'], cast: ['Albert Brooks', 'Ellen DeGeneres', 'Alexander Gould', 'Willem Dafoe', 'Brad Garrett'], g: 'Animation,Family', tag: 'There are 3.7 trillion fish in the ocean. They\'re looking for one.', kw: 'clownfish|father son relationship|great barrier reef|sydney|fish tank', c: 'G|U|G|G|U|0', pop: 75, aw: 'Won Best Animated Feature' },
  { id: 14160, t: 'Up', d: '2009-05-28', rt: 96, bo: 735099082, sc: 80, st: 'Pixar', dir: ['Pete Docter'], cast: ['Ed Asner', 'Christopher Plummer', 'Jordan Nagai', 'Bob Peterson', 'Delroy Lindo'], g: 'Animation,Comedy,Family,Adventure', tag: 'Adventure is out there.', kw: 'balloon|widower|south america|talking dog|wilderness explorer', c: 'PG|U|G|PG|U|0', pop: 70, aw: 'Won Best Animated Feature|Won Best Original Score' },
  { id: 8587, t: 'The Lion King', d: '1994-06-24', rt: 89, bo: 968483777, sc: 83, st: 'Disney', dir: ['Roger Allers', 'Rob Minkoff'], cast: ['Matthew Broderick', 'Jeremy Irons', 'James Earl Jones', 'Moira Kelly', 'Nathan Lane'], g: 'Family,Animation,Drama', tag: 'Life\'s greatest adventure is finding your place in the Circle of Life.', kw: 'lion|africa|uncle|exile|king', c: 'G|U|G|G|U|0', pop: 85, aw: 'Won Best Original Score|Won Best Original Song' },
  { id: 129, t: 'Spirited Away', ot: '千と千尋の神隠し', d: '2001-07-20', rt: 125, bo: 274925095, sc: 85, st: 'Studio Ghibli', dir: ['Hayao Miyazaki'], cast: ['Rumi Hiiragi', 'Miyu Irino', 'Mari Natsuki', 'Takashi Naito', 'Yasuko Sawaguchi'], g: 'Animation,Family,Fantasy', tag: null, kw: 'bathhouse|spirit world|witch|dragon|parents turned into pigs', c: 'PG|PG|G|PG||0', pop: 80, aw: 'Won Best Animated Feature', el: false },

  // 2010s and 2020s
  { id: 496243, t: 'Parasite', ot: '기생충', d: '2019-05-30', rt: 133, bo: 262676688, sc: 85, st: 'Neon', dir: ['Bong Joon-ho'], cast: ['Song Kang-ho', 'Lee Sun-kyun', 'Cho Yeo-jeong', 'Choi Woo-shik', 'Park So-dam'], g: 'Comedy,Thriller,Drama', tag: 'Act like you own the place.', kw: 'class differences|con artist|basement|rich family|seoul', c: 'R|15|14A|MA15+|A|16', pop: 80, aw: 'Won Best Picture|First non-English language Best Picture winner' },
  { id: 419430, t: 'Get Out', d: '2017-02-24', rt: 104, bo: 255407969, sc: 76, st: 'Universal', dir: ['Jordan Peele'], cast: ['Daniel Kaluuya', 'Allison Williams', 'Bradley Whitford', 'Catherine Keener', 'Caleb Landry Jones'], g: 'Mystery,Thriller,Horror', tag: 'Just because you\'re invited, doesn\'t mean you\'re welcome.', kw: 'hypnosis|meeting the parents|racism|sunken place|photographer', c: 'R|15|14A|MA15+|A|16', pop: 55, aw: 'Won Best Original Screenplay' },
  { id: 313369, t: 'La La Land', d: '2016-12-09', rt: 129, bo: 448906865, sc: 79, st: 'Lionsgate', dir: ['Damien Chazelle'], cast: ['Ryan Gosling', 'Emma Stone', 'John Legend', 'Rosemarie DeWitt', 'J.K. Simmons'], g: 'Comedy,Drama,Romance,Music', tag: 'Here\'s to the fools who dream.', kw: 'jazz pianist|aspiring actress|los angeles|musical|dream', c: 'PG-13|12A|PG|M|U|0', pop: 65, aw: 'Won 6 Oscars, including Best Director' },
  { id: 244786, t: 'Whiplash', d: '2014-10-10', rt: 107, bo: 48982041, sc: 84, st: 'Sony Pictures Classics', dir: ['Damien Chazelle'], cast: ['Miles Teller', 'J.K. Simmons', 'Paul Reiser', 'Melissa Benoist', 'Austin Stowell'], g: 'Drama,Music', tag: 'The road to greatness can take you to the edge.', kw: 'drummer|music conservatory|abusive teacher|jazz|ambition', c: 'R|15|14A|M||12', pop: 60, aw: 'Won 3 Oscars, including Best Supporting Actor' },
  { id: 376867, t: 'Moonlight', d: '2016-10-21', rt: 111, bo: 65046687, sc: 74, st: 'A24', dir: ['Barry Jenkins'], cast: ['Trevante Rhodes', 'André Holland', 'Janelle Monáe', 'Ashton Sanders', 'Mahershala Ali'], g: 'Drama', tag: 'This is the story of a lifetime.', kw: 'coming of age|miami|identity|three chapters|drug dealer', c: 'R|15|14A|MA15+||12', pop: 30, aw: 'Won Best Picture|Won Best Supporting Actor' },
  { id: 76341, t: 'Mad Max: Fury Road', d: '2015-05-13', rt: 121, bo: 378858340, sc: 76, st: 'Warner Bros.', dir: ['George Miller'], cast: ['Tom Hardy', 'Charlize Theron', 'Nicholas Hoult', 'Hugh Keays-Byrne', 'Rosie Huntington-Whiteley'], g: 'Action,Adventure,Science Fiction', tag: 'What a lovely day.', kw: 'post-apocalyptic|desert|car chase|war rig|escape', c: 'R|15|14A|MA15+|A|16', pop: 65, aw: 'Won 6 Oscars, the most of any film that year' },
  { id: 475557, t: 'Joker', d: '2019-10-01', rt: 122, bo: 1078958629, sc: 81, st: 'Warner Bros.', dir: ['Todd Phillips'], cast: ['Joaquin Phoenix', 'Robert De Niro', 'Zazie Beetz', 'Frances Conroy', 'Brett Cullen'], g: 'Crime,Thriller,Drama', tag: 'Put on a happy face.', kw: 'clown|stand-up comedian|gotham|mental illness|talk show', c: 'R|15|14A|MA15+|A|16', pop: 95, aw: 'Won Best Actor|Won Best Original Score' },
  { id: 489, t: 'Good Will Hunting', d: '1997-12-05', rt: 127, bo: 225933435, sc: 81, st: 'Miramax', dir: ['Gus Van Sant'], cast: ['Matt Damon', 'Robin Williams', 'Ben Affleck', 'Stellan Skarsgård', 'Minnie Driver'], g: 'Drama', tag: 'Some people can never believe in themselves, until someone believes in them.', kw: 'genius|janitor|therapist|boston|mathematics', c: 'R|15|14A|M||12', pop: 55, aw: 'Won Best Original Screenplay|Won Best Supporting Actor' },
  { id: 120467, t: 'The Grand Budapest Hotel', d: '2014-02-26', rt: 100, bo: 174600318, sc: 80, st: 'Searchlight', dir: ['Wes Anderson'], cast: ['Ralph Fiennes', 'Tony Revolori', 'F. Murray Abraham', 'Mathieu Amalric', 'Adrien Brody'], g: 'Comedy,Drama', tag: 'A perfect holiday without leaving the lobby.', kw: 'concierge|lobby boy|stolen painting|fictional country|prison break', c: 'R|15|14A|M||12', pop: 45, aw: 'Won 4 Oscars, including Best Production Design' },
  { id: 37165, t: 'The Truman Show', d: '1998-06-04', rt: 103, bo: 264118201, sc: 81, st: 'Paramount', dir: ['Peter Weir'], cast: ['Jim Carrey', 'Laura Linney', 'Noah Emmerich', 'Natascha McElhone', 'Ed Harris'], g: 'Comedy,Drama', tag: 'On the air. Unaware.', kw: 'reality show|hidden camera|small town|insurance salesman|escape', c: 'PG|PG|PG|PG||6', pop: 60 },
  { id: 161, t: 'Ocean\'s Eleven', d: '2001-12-07', rt: 116, bo: 450717150, sc: 74, st: 'Warner Bros.', dir: ['Steven Soderbergh'], cast: ['George Clooney', 'Brad Pitt', 'Matt Damon', 'Andy García', 'Julia Roberts'], g: 'Thriller,Crime', tag: 'Are you in or out?', kw: 'casino|heist|las vegas|ex-con|vault', c: 'PG-13|12|PG|M||6', pop: 60 },
  { id: 473033, t: 'Uncut Gems', d: '2019-12-13', rt: 135, bo: 50023780, sc: 70, st: 'A24', dir: ['Josh Safdie', 'Benny Safdie'], cast: ['Adam Sandler', 'Julia Fox', 'Idina Menzel', 'LaKeith Stanfield', 'Kevin Garnett'], g: 'Crime,Drama,Thriller', tag: 'This is how I win.', kw: 'jeweler|gambling addiction|opal|debt|new york city', c: 'R|15|18A|MA15+||16', pop: 30, el: false },
  { id: 493922, t: 'Hereditary', d: '2018-06-07', rt: 127, bo: 82464115, sc: 73, st: 'A24', dir: ['Ari Aster'], cast: ['Toni Collette', 'Alex Wolff', 'Milly Shapiro', 'Gabriel Byrne', 'Ann Dowd'], g: 'Horror,Mystery,Thriller', tag: 'Evil runs in the family.', kw: 'grief|miniature|cult|seance|family secret', c: 'R|15|14A|MA15+||16', pop: 40, el: false },
  { id: 281957, t: 'The Revenant', d: '2015-12-25', rt: 156, bo: 532950503, sc: 75, st: '20th Century', dir: ['Alejandro González Iñárritu'], cast: ['Leonardo DiCaprio', 'Tom Hardy', 'Will Poulter', 'Domhnall Gleeson', 'Forrest Goodluck'], g: 'Western,Drama,Adventure', tag: 'Blood lost. Life found.', kw: 'bear attack|frontier|fur trapper|survival|revenge', c: 'R|15|14A|MA15+|A|16', pop: 60, aw: 'Won Best Director|Won Best Actor|Won Best Cinematography' },
  { id: 546554, t: 'Knives Out', d: '2019-11-27', rt: 131, bo: 311949527, sc: 78, st: 'Lionsgate', dir: ['Rian Johnson'], cast: ['Daniel Craig', 'Chris Evans', 'Ana de Armas', 'Jamie Lee Curtis', 'Michael Shannon'], g: 'Comedy,Crime,Mystery', tag: 'Hell, any of them could have done it.', kw: 'whodunit|detective|inheritance|mansion|nurse', c: 'PG-13|12A|PG|M|UA|12', pop: 60 },
  { id: 661374, t: 'Glass Onion: A Knives Out Mystery', d: '2022-11-23', rt: 140, bo: null, sc: 71, st: 'Netflix', dir: ['Rian Johnson'], cast: ['Daniel Craig', 'Edward Norton', 'Janelle Monáe', 'Kathryn Hahn', 'Leslie Odom Jr.'], g: 'Comedy,Crime,Mystery', tag: null, kw: 'whodunit|detective|private island|tech billionaire|murder mystery party', c: 'PG-13|12A|PG|M||12', pop: 40 },
  { id: 361743, t: 'Top Gun: Maverick', d: '2022-05-24', rt: 131, bo: 1495696292, sc: 82, st: 'Paramount', dir: ['Joseph Kosinski'], cast: ['Tom Cruise', 'Miles Teller', 'Jennifer Connelly', 'Jon Hamm', 'Glen Powell'], g: 'Action,Drama', tag: 'Feel the need... The need for speed.', kw: 'fighter pilot|navy|flight school|sequel|mission', c: 'PG-13|12A|PG|M|UA|12', pop: 95, aw: 'Won Best Sound' },
  { id: 492188, t: 'Marriage Story', d: '2019-11-06', rt: 137, bo: null, sc: 77, st: 'Netflix', dir: ['Noah Baumbach'], cast: ['Adam Driver', 'Scarlett Johansson', 'Laura Dern', 'Alan Alda', 'Ray Liotta'], g: 'Drama', tag: null, kw: 'divorce|custody battle|theater director|los angeles|lawyer', c: 'R|15|14A|M||6', pop: 30, aw: 'Won Best Supporting Actress' },
  { id: 646380, t: 'Don\'t Look Up', d: '2021-12-07', rt: 138, bo: null, sc: 71, st: 'Netflix', dir: ['Adam McKay'], cast: ['Leonardo DiCaprio', 'Jennifer Lawrence', 'Meryl Streep', 'Cate Blanchett', 'Rob Morgan'], g: 'Comedy,Drama,Science Fiction', tag: 'Based on truly possible events.', kw: 'comet|astronomer|satire|president|media', c: 'R|15|14A|M||12', pop: 45 },
  { id: 153, t: 'Lost in Translation', d: '2003-09-12', rt: 102, bo: 118685453, sc: 74, st: 'Focus Features', dir: ['Sofia Coppola'], cast: ['Bill Murray', 'Scarlett Johansson', 'Giovanni Ribisi', 'Anna Faris', 'Fumihiro Hayashi'], g: 'Drama,Comedy,Romance', tag: 'Everyone wants to be found.', kw: 'tokyo|hotel|insomnia|karaoke|loneliness', c: 'R|15|14A|M||0', pop: 30, aw: 'Won Best Original Screenplay', el: false },
  { id: 38, t: 'Eternal Sunshine of the Spotless Mind', d: '2004-03-19', rt: 108, bo: 74036715, sc: 81, st: 'Focus Features', dir: ['Michel Gondry'], cast: ['Jim Carrey', 'Kate Winslet', 'Kirsten Dunst', 'Mark Ruffalo', 'Elijah Wood'], g: 'Science Fiction,Drama,Romance', tag: 'You can erase someone from your mind. Getting them out of your heart is another story.', kw: 'memory erasure|breakup|montauk|nonlinear timeline|relationship', c: 'R|15|14A|M||12', pop: 40, aw: 'Won Best Original Screenplay', el: false },
];
